#include <stdio.h>
#include "openssl/evp.h"
#include <string.h>

#define MAX_LENGTH 16 // A global variable t define max-length

int main (int argc, const char *argv[])
{
	/* This variable is used to store the ciphertext provided to you. Make sure to use the proper format, eg. the hex 'd23a' would be written as {0xd2,0x3a} in C */
	unsigned char ciphertxt[] = {0x20, 0x75, 0x38, 0x6b, 0x75, 0xee, 0xd8, 0xb4, 0xf2, 0xb4, 0xa9, 0xc9, 0xb7, 0x69, 0x67, 0xd0, 0x57, 0xb4, 0xa4, 0x41, 0xd3, 0x49, 0xc1, 0x5d, 0xd4, 0xb8, 0xbf, 0x4b, 0x87, 0x44, 0x5a, 0x9e};

	// This is the plaintext that we are encrypting. Do not change it as it may result in a different ciphertext
	char plaintext[]= "This is a top secret";

	// Pointer fp used to point to the English words file provided along.
	FILE *fp;

	// The initialization Vector is set to 0
	unsigned char iv[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

	// Output buffer set to 1024 size
	unsigned char outbuf [1024];

	// Some other variables that are used in the program
	int outlen = 0, tmplen = 0;
	/* You may want to declare some additional variables to be used as flags*/

	EVP_CIPHER_CTX ctx;
	fp = fopen("words.txt","r");

	if (/* Use this statement to check is the words.txt file can be opened in 'r' permission */ fp == NULL)
	{
		/* Print a statement if the above condition is not met */
		printf("File can't be opened\n");
		return 0;
	}

	char key [MAX_LENGTH]; //array to store the key getting from the dictionary

	while (fgets(key, MAX_LENGTH, fp) != NULL)
	{
		for(int i = 0; i < MAX_LENGTH; i++)
		{
			if (key[i] == '\n' || key[i] == 0 ) //when key is less than 16 characters, the extra left part is filled with " "
			{
				for (int j = i; j < strlen(key); j++)
				{
					key[j] = ' ';
				}
				break;
			}
		}

		// Use the EVP library to initialize cipher
		EVP_CIPHER_CTX_init (&ctx);

		// Use the EVP library to encrypt the cipher
		EVP_EncryptInit_ex (&ctx, EVP_aes_128_cbc(), NULL, key, iv);

		// Checking to see if EVP_EncryptUpdate is valid or not
		if (!EVP_EncryptUpdate (&ctx, outbuf, &outlen, plaintext, strlen(plaintext)))
		{
			/*Print Out a relevant Error Messege*/
			printf("Error\n");
			return 0;
		}

		// Buffer passed to EVP_EncryptFinal() must be after data just encrypted to avoid overwriting it

		// Checking to see if !EVP_EncryptFinal_ex is valid or not
		if (!EVP_EncryptFinal_ex (&ctx, outbuf + outlen, &tmplen))
		{
			/*Print Out a relevant Error Messege*/
			printf("Error\n");
			return 0;
		}

		outlen += tmplen;

		EVP_CIPHER_CTX_cleanup (&ctx);

		//print curret key and its corresponding ciphertext
		printf ("The key is : %s       The Corresponding Cipher Text Is:  ", key); 

		for(int j = 0; j < outlen; j++) 
		{
			/* Use a loop to print out the buffer */
			printf ("%x", outbuf[j]);
		}
		printf ("\n");

		for(int q = 0; q < outlen; q++)
		{
			/* Judge whether the cipher text generated by this key is match for the provoded one */
			/* As the whole ciphertext cannot be matched at once, use this loop to match it bit by bit */
			if(outbuf[q] != ciphertxt[q]) {
			outbuf[q] == ciphertxt[q];
			}
		}
			int result = memcmp(outbuf, ciphertxt, outlen);
		if (/* If the generated ciphertext matched with the one provided*/ result == 0)
		{
			printf ("\n*****************************************************\n");
			printf("The key is : %s\n", key);
			printf("\nThe cipher text using the above key is: \n");

			/* Print the key used */
			for(int j = 0; j < outlen; j++)
			{
				printf("%x", outbuf[j]);
			}

			printf("\n");

			printf("The cipher text we were searching for is: \n");
			
			/* Print the text in the output buffer */
			
			
			/* Print the provided ciphertext*/
			for( int i = 0; i<sizeof(ciphertxt); ++i)
			{
				printf("%x", ciphertxt[i]);
			}

			printf("\n");

			/* Print the length of the ciphertext */
			int len = sizeof(ciphertxt);
			printf("The length of the ciphertext is: %d\n", len);		
			printf ("\n*****************************************************\n");
			return 0;
		}
	}
	fclose (fp);
	return 0;
}
